version: '3.1'

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=flask_home
    ports:
      - 5432:5432

  flask_app:
    restart: always
    build: .
    ports:
      - 5000:5000
    depends_on:
      - pg_db
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379