####
# просмотр почты
GET http://127.0.0.1:5000/email/c2b483df-c10e-4355-b6e1-6a32f4b713ec
content-type: application/json
####
####
# просмотр почты
POST http://127.0.0.1:5000/email-send/2
content-type: application/json
####
####
# просмотр почт
POST http://127.0.0.1:5000/email-send-all/
content-type: application/json
####


####
# просмотр пользователь
GET http://127.0.0.1:5000/api/users/2
content-type: application/json
####

####
# регистрация1
POST http://127.0.0.1:5000/api/login/
content-type: application/json

{
  "username": "tester1",
  "email": "maxtv@mail.ru",
  "password": "111EEeeetr"
}
####"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTUxMTUyODIsIm5iZiI6MTYxNTExNTI4MiwianRpIjoiOWFkNTgyYzgtNGY1Ny00ZDNkLThjOTUtMzE0NWE5YzA4MmMwIiwiZXhwIjoxNjE1NzIwMDgyLCJpZGVudGl0eSI6IjEiLCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MifQ.v_LyG7AkbZQ-QK0EplEVHlKoSn12y0I3N607lq9QFmg"

####
# регистрация2
POST http://127.0.0.1:5000/api/login/
content-type: application/json

{
  "username": "tester2",
  "email": "m.trunov@severen.ru",
  "password": "11qwerty2"
}
####eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTQ5NjU1MDgsIm5iZiI6MTYxNDk2NTUwOCwianRpIjoiNjU2MmU3MTAtMDk0MS00NDBhLWJhZDctMjA1ODA1YWU1NzUzIiwiZXhwIjoxNjE1NTcwMzA4LCJpZGVudGl0eSI6IjIiLCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MifQ.Q5mjpjI-agr86OuzieuNd-yA7mGhcNYFsOfAAyt67MA


####
# просморт всех объявлений
GET http://127.0.0.1:5000/api/posts/
content-type: application/json
####

####
# просморт одного объявления
GET http://127.0.0.1:5000/api/posts/14
content-type: application/json
####

####
# добавление объявления 1
POST http://127.0.0.1:5000/api/posts/
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTQ0NTg3NzEsIm5iZiI6MTYxNDQ1ODc3MSwianRpIjoiYWUyMjQ1YTgtZDkyMy00NzEwLWJlOTgtYmRmNTZiOTQzMmM2IiwiZXhwIjoxNjE1MDYzNTcxLCJpZGVudGl0eSI6IjEiLCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MifQ.bb1hv2mO76rHmESykz1GLQNa96U30FCalzlaszWHSOQ

{
  "title": "test1",
  "content": "This is test content"
}
####

####
# добавление объявления 2
POST http://127.0.0.1:5000/api/posts/
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MDgzNzQ4NjYsIm5iZiI6MTYwODM3NDg2NiwianRpIjoiZjk4N2QxNDYtZTlhZi00MTRhLTkyNjktMjJhZWM0ZjQwN2MxIiwiZXhwIjoxNjA4OTc5NjY2LCJpZGVudGl0eSI6IjgiLCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MifQ.BcVhXXTJJT9y9S-P5MNon4WDLUCjImKJvQp3LL_AgkE

{
  "title": "test2",
  "content": "This is test content"
}
####

# удаление объявления
DELETE http://127.0.0.1:5000/api/posts/14
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MDgzNzQ4NjYsIm5iZiI6MTYwODM3NDg2NiwianRpIjoiZjk4N2QxNDYtZTlhZi00MTRhLTkyNjktMjJhZWM0ZjQwN2MxIiwiZXhwIjoxNjA4OTc5NjY2LCJpZGVudGl0eSI6IjgiLCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MifQ.BcVhXXTJJT9y9S-P5MNon4WDLUCjImKJvQp3LL_AgkE
####

# обновление объявления
PUT http://127.0.0.1:5000/api/posts/13
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MDgzNzQ4NjYsIm5iZiI6MTYwODM3NDg2NiwianRpIjoiZjk4N2QxNDYtZTlhZi00MTRhLTkyNjktMjJhZWM0ZjQwN2MxIiwiZXhwIjoxNjA4OTc5NjY2LCJpZGVudGl0eSI6IjgiLCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MifQ.BcVhXXTJJT9y9S-P5MNon4WDLUCjImKJvQp3LL_AgkE

{
  "title": "test2",
  "content": "This is new new test content"
}

####

