POSTGRE_HOST = '127.0.0.1'
POSTGRE_PORT = '5432'
POSTGRE_USER = 'postgres'
POSTGRE_PASSWORD = 'maximus98'
POSTGRE_DATABASE = 'aiohttp'
POSTGRE_DSN = f'postgres://{POSTGRE_USER}:{POSTGRE_PASSWORD}@{POSTGRE_HOST}:{POSTGRE_PORT}/{POSTGRE_DATABASE}'
SQLALCHEMY_TRACK_MODIFICATIONS = False

JWT_SECRET = 't1NP63m4wnBg6nyHYKfmc2TpCOGI4nss'
JWT_ALGORITHM = 'HS256'
