version: '3.1'

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=flask_home
    ports:
      - 5432:5432

  app-flask:
    restart: always
    build: .
    ports:
      - 8900:5000
    depends_on:
      - pg_db


